# Infomail för hemma/borta
- alias: mail
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.home,device_tracker.sunnys_iphone
      to: "home"
  action:
    - service: script.notify
      data_template:
        title: '{{ trigger.to_state.attributes.friendly_name }} är hemma och röjer igen {{ now().strftime("%H:%M") }}!'
        message: |
          Bharani: {{states("device_tracker.sunnys_iphone")}}
